server:
  port: 8888

spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    connect-timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5

  thymeleaf:
    cache: false
    prefix: classpath:/templates/
